### ISSUE TITLE
app.component.ts 编译不通过

### ISSUE THREAD

**Issue by cpplm** [alexspring123/NG-ZORRO-TEMPLATE#1]
ERROR in NG-ZORRO-TEMPLATE/src/app/app.component.ts (19,8): Property 'filter' does not exist on type 'Observable<Event>'.

跟我的CLI版本有关系？

Your global Angular CLI version (1.3.1) is greater than your local
version (1.1.2). The local Angular CLI version is used.

**Comment by alexspring123** [comment]
感谢反馈，我刚推送了一个版本，你再试试

下面是我的版本
localhost:ng-zorro-demo alex$ ng --version
```
@angular/cli: 1.1.2
node: 6.10.2
os: darwin x64
@angular/animations: 4.3.5
@angular/common: 4.3.5
@angular/compiler: 4.3.5
@angular/core: 4.3.5
@angular/forms: 4.3.5
@angular/http: 4.3.5
@angular/platform-browser: 4.3.5
@angular/platform-browser-dynamic: 4.3.5
@angular/router: 4.3.5
@angular/cli: 1.1.2
@angular/compiler-cli: 4.3.5
@angular/language-service: 4.3.5
```

**Comment by iedwin** [comment]
@alexspring123 
看来新版本还是编译不过。
<img width="1265" alt="screen shot 2017-08-22 at 10 59 07 pm" src="https://user-images.githubusercontent.com/17739715/29572032-a6b0b85a-8720-11e7-8c2d-3ca28ffa03ff.png">

**Comment by alexspring123** [comment]
已经修复；
