### ISSUE TITLE
菜单怎么跑上面去了？

### ISSUE THREAD

**Issue by wangying11** [alexspring123/NG-ZORRO-TEMPLATE#14]

**Comment by alexspring123** [comment]
通过[global-config.ts](https://github.com/alexspring123/NG-ZORRO-TEMPLATE/blob/master/src/config/global-config.ts)中的menuConfig进行配置  
我的在线Demo配成了“top”，你可以clone后自行更改
```
// menu配置
export const menuConfig = {
    // 菜单位置，可选值为 'left'、'top'
    placement: 'top'
}
```
